Repository robotology/assistive-rehab, pull requests merged in 2019-09, with the labels that each got.

#204 motionAnalyzer refactored to account for different exercises
  app/conf/train-with-me/abduction_left.ini
  app/conf/train-with-me/motionAnalyzer.ini
  app/scripts/AssistiveRehab-faces.xml.template
  app/scripts/AssistiveRehab.xml.template
  app/scripts/train-with-me/AssistiveRehab-TWM-robot.xml.template
  app/scripts/train-with-me/AssistiveRehab-TWM-virtual.xml.template
  modules/feedbackProducer/src/main.cpp
  modules/interactionManager/src/main.cpp
  modules/motionAnalyzer/app/conf/abduction_left.ini
  modules/motionAnalyzer/app/conf/external_rotation_left.ini
  modules/motionAnalyzer/app/conf/internal_rotation_left.ini
  modules/motionAnalyzer/app/conf/motion-repertoire-left.ini
  modules/motionAnalyzer/app/conf/motion-repertoire-rom-left.ini
  modules/motionAnalyzer/app/conf/motion-repertoire-rom12.ini
  modules/motionAnalyzer/app/conf/motion-repertoire-rom3-left.ini
  modules/motionAnalyzer/app/conf/motion-repertoire-rom6.ini
  modules/motionAnalyzer/app/conf/motion-repertoire.ini
  modules/motionAnalyzer/app/conf/reaching_left.ini
  modules/motionAnalyzer/app/conf/tug.ini
  modules/motionAnalyzer/include/Exercise.h
  modules/motionAnalyzer/include/Manager.h
  modules/motionAnalyzer/include/Metric.h
  modules/motionAnalyzer/include/Processor.h
  modules/motionAnalyzer/motionAnalyzer.xml
  modules/motionAnalyzer/src/Exercise.cpp
  modules/motionAnalyzer/src/Manager.cpp
  modules/motionAnalyzer/src/Metric.cpp
  modules/motionAnalyzer/src/Processor.cpp
  modules/motionAnalyzer/src/idl.thrift
  report/ProgrammaticReport-eng.ipynb
  report/ProgrammaticReport-ita.ipynb
  report/report-eng.ipynb
  report/report-ita.ipynb
Labels: 🚀 enhancement

#217 Replace yarp::os::Mutex with std::mutex
  modules/actionRecognizer/src/main.cpp
  modules/attentionManager/src/main.cpp
  modules/faceRecognizer/include/queryThread.h
  modules/faceRecognizer/src/main.cpp
  modules/faceRecognizer/src/queryThread.cpp
  modules/feedbackProducer/src/main.cpp
  modules/interactionManager/src/main.cpp
  modules/motionAnalyzer/include/Manager.h
  modules/motionAnalyzer/src/Manager.cpp
  modules/robotSkeletonPublisher/src/main.cpp
  modules/skeletonPlayer/src/main.cpp
  modules/skeletonViewer/main.cpp
Labels: ✨improvement

#218 [actionRecognition] fixed std mutex conflicts with tensorflow mutex
  modules/actionRecognizer/src/main.cpp
Labels: 🐞 bug

#219 Added simple base navigation
  modules/CMakeLists.txt
  modules/navController/CMakeLists.txt
  modules/navController/navController.xml
  modules/navController/src/idl.thrift
  modules/navController/src/main.cpp
  tests/CMakeLists.txt
  tests/test-nav.cpp
Labels: 🚀 enhancement
