Repository robotology/assistive-rehab, pull requests merged in 2019-11, with the labels that each got.

#239 Integrate speech in TUG
  app/scripts/AssistiveRehab-TUG.xml.template
  modules/managerTUG/app/conf/speak-en.ini
  modules/managerTUG/app/conf/speak-it.ini
  modules/managerTUG/src/main.cpp
  modules/motionAnalyzer/include/Manager.h
  modules/motionAnalyzer/src/Manager.cpp
  modules/motionAnalyzer/src/idl.thrift
Labels: 🚀 enhancement

#240 Added pointing actions
  app/scripts/AssistiveRehab-TUG.xml.template
  modules/managerTUG/app/conf/config-en.ini
  modules/managerTUG/app/conf/config-it.ini
  modules/managerTUG/src/main.cpp
Labels: 🚀 enhancement

#243 Build on Windows modules depending on FFTW3
  CMakeLists.txt
  cmake/linux/FindFFTW3.cmake
  cmake/linux/FindMATIO.cmake
  modules/feedbackProducer/CMakeLists.txt
  modules/feedbackProducer/src/main.cpp
Labels: ✨improvement

#242 Added CI via GitHub Actions
  .github/workflows/main.yml
Labels: 🚀 enhancement

#245 humanStructure overhaul
  modules/humanStructure/CMakeLists.txt
  modules/humanStructure/humanStructure.thrift
  modules/humanStructure/humanStructure.xml
  modules/humanStructure/main.cpp
Labels: ✨improvement, 🚀 enhancement
