Repository robotology/assistive-rehab, pull requests merged in 2020-01, with the labels that each got.

#255 Patch for CI on Windows
  .github/workflows/ci.yml
Labels: 🐞 bug

#256 navController uses yarp::dev::OdometryData
  CMakeLists.txt
  modules/navController/src/main.cpp
Labels: 🔼 upgrade

#258 Improve speech
  modules/speechInteraction/modules/googleSpeechProcess/app/conf/config.ini
  modules/speechInteraction/modules/googleSpeechProcess/main.cpp
Labels: ✨improvement

#260 Enable OpenCV 4
  .github/workflows/ci.yml
  modules/faceRecognizer/include/queryThread.h
Labels: 🔼 upgrade
